In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [8]:
X_train

age  gender  fever   cough       city
93   27    Male  100.0    Mild    Kolkata
40   49  Female  102.0    Mild      Delhi
88    5  Female  100.0    Mild    Kolkata
0    60    Male  103.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
31   83    Male  103.0    Mild    Kolkata
51   11  Female  100.0  Strong    Kolkata
41   82    Male    NaN    Mild    Kolkata
47   18  Female  104.0    Mild  Bangalore
9    64  Female  101.0    Mild      Delhi

[80 rows x 5 columns]

In [11]:
X_train['cough'].value_counts()

Mild      50
Strong    30
Name: cough, dtype: int64

## 1. Aam Zindagi

In [9]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [13]:
X_train_fever

array([[100.        ],
       [102.        ],
       [100.        ],
       [103.        ],
       [100.        ],
       [100.78873239],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [102.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [100.78873239],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [ 99.        ],
       [100.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [100.78873239],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [100.78873239],
       [100.78873239],
       [ 99.        ],
       [100.        ],
       [100

In [10]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [12]:
X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],

In [14]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [15]:
X_train_gender_city

array([[1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],


In [17]:
X_train.columns

Index(['age', 'gender', 'fever', 'cough', 'city'], dtype='object')

In [19]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [20]:
X_train_age

array([[27],
       [49],
       [ 5],
       [60],
       [19],
       [38],
       [24],
       [82],
       [51],
       [ 8],
       [56],
       [42],
       [69],
       [ 5],
       [34],
       [71],
       [83],
       [79],
       [66],
       [54],
       [47],
       [59],
       [72],
       [13],
       [82],
       [65],
       [14],
       [34],
       [19],
       [83],
       [60],
       [ 6],
       [34],
       [22],
       [16],
       [81],
       [55],
       [51],
       [65],
       [20],
       [42],
       [25],
       [10],
       [84],
       [81],
       [34],
       [70],
       [44],
       [40],
       [69],
       [27],
       [31],
       [14],
       [20],
       [23],
       [48],
       [47],
       [23],
       [80],
       [12],
       [17],
       [49],
       [16],
       [11],
       [ 5],
       [71],
       [20],
       [65],
       [27],
       [15],
       [65],
       [69],
       [12],
       [73],
       [38],
       [83],
       [11],

In [21]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [23]:
X_train_transformed

array([[ 27.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 49.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [  5.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 60.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 38.        , 100.78873239,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 24.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          1.    

## Mentos Zindagi

In [24]:
from sklearn.compose import ColumnTransformer

In [26]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [27]:
transformer.fit_transform(X_train).shape

(80, 7)

In [28]:
transformer.transform(X_test).shape

(20, 7)