In [618]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from  sklearn.impute import SimpleImputer, MissingIndicator

In [619]:
df = pd.read_csv('/content/train.csv')
df.head()

Year_Factor State_Factor building_class  \
0            1      State_1     Commercial   
1            1      State_1     Commercial   
2            1      State_1     Commercial   
3            1      State_1     Commercial   
4            1      State_1     Commercial   

                               facility_type  floor_area  year_built  \
0               Grocery_store_or_food_market     61242.0      1942.0   
1  Warehouse_Distribution_or_Shipping_center    274000.0      1955.0   
2                       Retail_Enclosed_mall    280025.0      1951.0   
3                  Education_Other_classroom     55325.0      1980.0   
4                  Warehouse_Nonrefrigerated     66000.0      1985.0   

   energy_star_rating  ELEVATION  january_min_temp  january_avg_temp  ...  \
0                11.0        2.4                36              50.5  ...   
1                45.0        1.8                36              50.5  ...   
2                97.0        1.8                36              50.5  ...   
3                46.0        1.8                36              50.5  ...   
4               100.0        2.4                36              50.5  ...   

   days_above_80F  days_above_90F  days_above_100F  days_above_110F  \
0              14               0                0                0   
1              14               0                0                0   
2              14               0                0                0   
3              14               0                0                0   
4              14               0                0                0   

   direction_max_wind_speed  direction_peak_wind_speed  max_wind_speed  \
0                       1.0                        1.0             1.0   
1                       1.0                        NaN             1.0   
2                       1.0                        NaN             1.0   
3                       1.0                        NaN             1.0   
4                       1.0                        1.0             1.0   

   days_with_fog    site_eui  id  
0            NaN  248.682615   0  
1           12.0   26.500150   1  
2           12.0   24.693619   2  
3           12.0   48.406926   3  
4            NaN    3.899395   4  

[5 rows x 64 columns]

In [620]:
df['site_eui'].isnull().sum()

0

In [621]:
df['site_eui'] = np.where(df['site_eui'].isnull(), 1, 0)

In [622]:
X = df[['floor_area', 'energy_star_rating', 'max_wind_speed']]
y = df['site_eui']

In [623]:
df['site_eui'].isnull().sum()

0

In [624]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 22)

In [625]:
X_train_original = X_train.copy()
X_test_original = X_test.copy()

In [626]:
X_train_original.head()

floor_area  energy_star_rating  max_wind_speed
26391    171003.0                 NaN             NaN
32261     67560.0                 NaN             1.0
33162    127000.0                 NaN             NaN
62776     87260.0                58.0             NaN
8621      74874.0                 NaN             NaN

In [627]:
X_test_original

floor_area  energy_star_rating  max_wind_speed
69856     39900.0                30.0             NaN
72351    151450.0                84.0             NaN
64645     51780.0                61.0             1.0
6362     366128.0                67.0             1.0
70826     41030.0                74.0             NaN
...           ...                 ...             ...
6628     195421.0                78.0             NaN
53994     50400.0                93.0             1.0
36013     98203.0                 NaN             1.0
19210     60900.0                 NaN             1.0
33091    163197.0                 NaN             NaN

[22728 rows x 3 columns]

##numpy.where(condition, [x, y, ]/)

###Return elements chosen from x or y depending on condition.

------------------------------------------------------------------
#a = np.arange(10)
#a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#np.where(a < 5, a, 10*a)
array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [628]:
#missing indicator using for loop, missing:0 and not-missing:1
for var in ['floor_area', 'energy_star_rating', 'max_wind_speed']:
    X_train[var + '_missing'] = np.where(X_train[var].isnull(), 1, 0) #missing 0, not missing 1
    X_test[var + '_missing'] = np.where(X_test[var].isnull(), 1, 0)

In [629]:
X_train.head()

floor_area  energy_star_rating  max_wind_speed  floor_area_missing  \
26391    171003.0                 NaN             NaN                   0   
32261     67560.0                 NaN             1.0                   0   
33162    127000.0                 NaN             NaN                   0   
62776     87260.0                58.0             NaN                   0   
8621      74874.0                 NaN             NaN                   0   

       energy_star_rating_missing  max_wind_speed_missing  
26391                           1                       1  
32261                           1                       0  
33162                           1                       1  
62776                           0                       1  
8621                            1                       1

In [630]:
X_train.shape

(53029, 6)

In [631]:
X_train['energy_star_rating'].isnull().sum()

18624

In [632]:
X_train['energy_star_rating_missing'].sum()

18624

In [633]:
X_train['energy_star_rating_missing'].isnull().sum()

0

In [634]:
#sklearn add_indicator
imputer = SimpleImputer(strategy="mean",add_indicator=True)
X_train_original_transformed = imputer.fit_transform(X_train_original)
X_test_original_transformed = imputer.transform(X_test_original)

In [635]:
X_test_original_transformed

array([[3.99000000e+04, 3.00000000e+01, 4.17871095e+00, 0.00000000e+00,
        1.00000000e+00],
       [1.51450000e+05, 8.40000000e+01, 4.17871095e+00, 0.00000000e+00,
        1.00000000e+00],
       [5.17800000e+04, 6.10000000e+01, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       ...,
       [9.82030000e+04, 6.10320302e+01, 1.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [6.09000000e+04, 6.10320302e+01, 1.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [1.63197000e+05, 6.10320302e+01, 4.17871095e+00, 1.00000000e+00,
        1.00000000e+00]])

In [636]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

In [637]:
reg = LinearRegression()
reg.fit(X_train_original_transformed, y_train)

LinearRegression()

In [638]:
y_pred = reg.predict(X_test_original_transformed)

In [639]:
r2_score(y_test, y_pred)

1.0

In [640]:
mean_absolute_error(y_test, y_pred)

0.0

In [641]:
df = pd.read_csv('/content/train.csv')
df.head()

Year_Factor State_Factor building_class  \
0            1      State_1     Commercial   
1            1      State_1     Commercial   
2            1      State_1     Commercial   
3            1      State_1     Commercial   
4            1      State_1     Commercial   

                               facility_type  floor_area  year_built  \
0               Grocery_store_or_food_market     61242.0      1942.0   
1  Warehouse_Distribution_or_Shipping_center    274000.0      1955.0   
2                       Retail_Enclosed_mall    280025.0      1951.0   
3                  Education_Other_classroom     55325.0      1980.0   
4                  Warehouse_Nonrefrigerated     66000.0      1985.0   

   energy_star_rating  ELEVATION  january_min_temp  january_avg_temp  ...  \
0                11.0        2.4                36              50.5  ...   
1                45.0        1.8                36              50.5  ...   
2                97.0        1.8                36              50.5  ...   
3                46.0        1.8                36              50.5  ...   
4               100.0        2.4                36              50.5  ...   

   days_above_80F  days_above_90F  days_above_100F  days_above_110F  \
0              14               0                0                0   
1              14               0                0                0   
2              14               0                0                0   
3              14               0                0                0   
4              14               0                0                0   

   direction_max_wind_speed  direction_peak_wind_speed  max_wind_speed  \
0                       1.0                        1.0             1.0   
1                       1.0                        NaN             1.0   
2                       1.0                        NaN             1.0   
3                       1.0                        NaN             1.0   
4                       1.0                        1.0             1.0   

   days_with_fog    site_eui  id  
0            NaN  248.682615   0  
1           12.0   26.500150   1  
2           12.0   24.693619   2  
3           12.0   48.406926   3  
4            NaN    3.899395   4  

[5 rows x 64 columns]

In [642]:
X = df[['floor_area', 'energy_star_rating', 'max_wind_speed']]
y = df['site_eui']

In [643]:
 from sklearn.impute import MissingIndicator
 indicator = MissingIndicator()
 X_indicator = indicator.fit_transform(X)
 X_indicator

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [ True,  True],
       [ True,  True],
       [False,  True]])

In [644]:
df2 = pd.DataFrame(X_indicator)
df2

0      1
0      False  False
1      False  False
2      False  False
3      False  False
4      False  False
...      ...    ...
75752  False   True
75753  False   True
75754   True   True
75755   True   True
75756  False   True

[75757 rows x 2 columns]

In [645]:
df3 = pd.concat([df1, df2],axis=1, ignore_index=True, sort=False)
df3

0     1    2      3      4
26391  171003.0   NaN  NaN   True   True
32261   67560.0   NaN  1.0   True  False
33162  127000.0   NaN  NaN   True   True
62776   87260.0  58.0  NaN  False   True
8621    74874.0   NaN  NaN   True   True
...         ...   ...  ...    ...    ...
75744       NaN   NaN  NaN  False   True
75747       NaN   NaN  NaN  False   True
75752       NaN   NaN  NaN  False   True
75753       NaN   NaN  NaN  False   True
75755       NaN   NaN  NaN   True   True

[75757 rows x 5 columns]

In [647]:
#X = df3[['floor_area', 'energy_star_rating', 'max_wind_speed']]
#y = df3['site_eui']
X = df3.iloc[:,:]
y = df['site_eui']
X

0     1    2      3      4
26391  171003.0   NaN  NaN   True   True
32261   67560.0   NaN  1.0   True  False
33162  127000.0   NaN  NaN   True   True
62776   87260.0  58.0  NaN  False   True
8621    74874.0   NaN  NaN   True   True
...         ...   ...  ...    ...    ...
75744       NaN   NaN  NaN  False   True
75747       NaN   NaN  NaN  False   True
75752       NaN   NaN  NaN  False   True
75753       NaN   NaN  NaN  False   True
75755       NaN   NaN  NaN   True   True

[75757 rows x 5 columns]

In [648]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 22)
X_train

0    1    2      3      4
2806    19384.0  NaN  NaN   True   True
69949   22058.0  1.0  NaN  False   True
70462   45500.0  NaN  NaN   True   True
32564       NaN  NaN  NaN  False   True
61571  184745.0  3.0  NaN  False   True
...         ...  ...  ...    ...    ...
17030       NaN  NaN  NaN   True  False
39807  175885.0  1.0  1.0  False  False
28968   72000.0  NaN  NaN   True   True
22284   86100.0  NaN  1.0   True  False
449     36518.0  NaN  1.0   True  False

[53029 rows x 5 columns]

##where **on** specifies field name that **exists in both dataframes** to join on, and **how** defines whether its **inner/outer/left/right** join, with **outer using 'union of keys from both frames (SQL: full outer join).'**

#In case, you want to **merge two DataFrames horizontally,** then use this code:

##df3 = pd.concat([df1, df2],axis=1, ignore_index=True, sort=False)

In [649]:
#df3 = pd.concat([df1, df2],axis=1, ignore_index=True, sort=False)
#df3 = pd.merge(df1, df2,on='common_column_on_both_dfs',how='outer')
